version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data_one:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
        
  wordpress:
    image: wordpress
    ports:
      - 2011:80
    restart: always
    volumes: ["./word_one:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db
volumes:
    db_data:
    wordpress:
